---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-xwiki-props 
  namespace: default
data:
  xwiki.properties: |
    environment.permanentDirectory=/var/local/xwiki/data/
    extension.oldflavors=org.xwiki.enterprise:xwiki-enterprise-ui-mainwiki
    extension.oldflavors=org.xwiki.enterprise:xwiki-enterprise-ui-wiki
    extension.oldflavors=org.xwiki.manager:xwiki-manager-ui
    extension.oldflavors=org.xwiki.manager:xwiki-manager-wiki-administrator
    extension.oldflavors=org.xwiki.manager:xwiki-enterprise-manager-wiki-administrator
    extension.oldflavors=com.xpn.xwiki.products:xwiki-enterprise-manager-wiki-administrator
    extension.oldflavors=com.xpn.xwiki.products:xwiki-enterprise-wiki
  xwiki.cfg: |
    xwiki.encoding=UTF-8
    xwiki.section.edit=1
    xwiki.section.depth=2
    xwiki.backlinks=1
    xwiki.tags=1
    xwiki.store.migration=1
    xwiki.store.migration.databases=all
    xwiki.inactiveuser.allowedpages=
    xwiki.superadminpassword=xwiki1
    xwiki.authentication.validationKey=totototototototototototototototo
    xwiki.authentication.encryptionKey=titititititititititititititititi
    xwiki.authentication.cookiedomains=k8s.senia.org
    xwiki.authentication.logoutpage=(/|/[^/]+/|/wiki/[^/]+/)logout/*
    xwiki.editcomment=1
    xwiki.editcomment.mandatory=0
    xwiki.defaultskin=flamingo
    xwiki.defaultbaseskin=flamingo
    xwiki.plugins=com.xpn.xwiki.monitor.api.MonitorPlugin,com.xpn.xwiki.plugin.skinx.JsSkinExtensionPlugin,com.xpn.xwiki.plugin.skinx.JsSkinFileExtensionPlugin,com.xpn.xwiki.plugin.skinx.JsResourceSkinExtensionPlugin,com.xpn.xwiki.plugin.skinx.CssSkinExtensionPlugin,com.xpn.xwiki.plugin.skinx.CssSkinFileExtensionPlugin,com.xpn.xwiki.plugin.skinx.CssResourceSkinExtensionPlugin,com.xpn.xwiki.plugin.skinx.LinkExtensionPlugin,com.xpn.xwiki.plugin.feed.FeedPlugin,com.xpn.xwiki.plugin.mail.MailPlugin,com.xpn.xwiki.plugin.packaging.PackagePlugin,com.xpn.xwiki.plugin.svg.SVGPlugin,com.xpn.xwiki.plugin.fileupload.FileUploadPlugin,com.xpn.xwiki.plugin.image.ImagePlugin,com.xpn.xwiki.plugin.diff.DiffPlugin,com.xpn.xwiki.plugin.rightsmanager.RightsManagerPlugin,com.xpn.xwiki.plugin.jodatime.JodaTimePlugin,com.xpn.xwiki.plugin.scheduler.SchedulerPlugin,com.xpn.xwiki.plugin.mailsender.MailSenderPlugin,com.xpn.xwiki.plugin.tag.TagPlugin,com.xpn.xwiki.plugin.zipexplorer.ZipExplorerPlugin
    xwiki.plugin.image.cache.capacity=30
    xwiki.stats.default=0
